---
name: test

releases:
- name: mapfs
  version: create
  url: file://.

stemcells:
- alias: default
  os: ((os))
  version: latest

update:
  canaries: 1
  max_in_flight: 1
  canary_watch_time: 5000-60000
  update_watch_time: 5000-60000

instance_groups:
- name: mapfs
  azs: [z1]
  instances: 1
  jobs:
  - name: mapfs
    release: mapfs
    properties: {}
  vm_type: default
  stemcell: default
  networks:
  - name: default
